version: '3.8'

services:
    postgres:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data

    airflow-webserver:
        image: apache/airflow:2.10.5
        restart: always
        depends_on:
            - postgres
        environment:
            AIRFLOW__CORE__EXECUTOR: LocalExecutor
            AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
            AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        volumes:
            - ./dags:/opt/airflow/dags
            - ../weather:/opt/airflow/weather
            - ../weather_data_loader:/opt/airflow/weather_data_loader
            - ../storage:/opt/airflow/storage
            - ../config:/opt/airflow/congfig
            - ../requirements.txt:/requirements.txt
        ports:
            - "8080:8080"
        command: bash -c "pip install -r /requirements.txt && airflow webserver"

    airflow-scheduler:
        image: apache/airflow:2.10.5
        restart: always
        depends_on:
            - airflow-webserver
        environment:
            AIRFLOW__CORE__EXECUTOR: LocalExecutor
            AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        volumes:
            - ./dags:/opt/airflow/dags
            - ../weather:/opt/airflow/weather
            - ../weather_data_loader:/opt/airflow/weather_data_loader
            - ../storage:/opt/airflow/storage
            - ../config:/opt/airflow/config
            - ../requirements.txt:/requirements.txt
        command: bash -c "pip install -r /requirements.txt && airflow scheduler"

    airflow-init:
      image: apache/airflow:2.10.5
      depends_on:
        - postgres
        - airflow-webserver
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      volumes:
        - ../dags:/opt/airflow/dags
        - ../weather:/opt/airflow/weather
        - ../weather_data_loader:/opt/airflow/weather_data_loader
        - ../storage:/opt/airflow/storage
        - ../config:/opt/airflow/config
      entrypoint: >
        bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com"

volumes:
    postgres-db-volume: